services:
  backend:
    build:
      context: ./backend
      dockerfile: ImmichDownloader.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/immich_downloader.db
      - Jwt__Key=my-super-secret-jwt-key-for-development-only-please-change-in-production
      - Jwt__Issuer=ImmichDownloader
      - Jwt__Audience=ImmichDownloader
      - Jwt__ExpireMinutes=30
    volumes:
      - backend-data:/app/data
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  test-server:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./test:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  backend-data: