version: '3.9'

services:
  backend:
    container_name: immich-downloader-backend
    build:
      context: ./backend
      dockerfile: ImmichDownloader.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/immich_downloader.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SKIP_VALIDATION=true
      - Jwt__Issuer=${JWT_ISSUER:-ImmichDownloader}
      - Jwt__Audience=${JWT_AUDIENCE:-ImmichDownloader}
      - Jwt__TokenLifetimeHours=${JWT_TOKEN_LIFETIME_HOURS:-24}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8082,http://127.0.0.1:8082
    volumes:
      - backend-data:/app/data
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    container_name: immich-downloader-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    container_name: immich-downloader-nginx
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend

volumes:
  backend-data: